# Generated by Django 3.2 on 2022-03-27 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.CASCADE, to='theblog.category'),
        ),
    ]
