# Generated by Django 3.2 on 2022-03-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0017_alter_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='snippet',
        ),
    ]
